language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-allforabit' ]; then cd .. && eval "mv $currentfolder generator-allforabit" && cd generator-allforabit; fi
